ep3finalmentepqp-master/shop/config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :products do
    resources :reviews, except: [:show, :index]
  end
  devise_for :users, controllers:  {
    registrations: 'registrations'
  }
  root 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

ep3finalmentepqp-master/shop/app/models/product.rb
class Product < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  has_many :line_items
  belongs_to :user, optional: true
  mount_uploader :image, ImageUploader
  serialize :image, JSON

  validates :name, :price, :tag, presence: true
  validates :description, length: { maximum: 1000, too_long: "%{count} é o número máximo de caracteres permitido. "}
  validates :name, length: { maximum: 300, too_long: "%{count} é o número máximo de caracteres permitido. "}
  validates :price, length: { maximum: 10 }

  TAG = %w{ Eletrodomésticos Hardware Áudio }

  private
    def not_referenced_by_any_line_item
      unless line_items.empty?
        errors.add(:base, "Line items present")
        throw :abort
      end
  end
end

ep3finalmentepqp-master/shop/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.order("created_at desc")
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @reviews = Review.where(product_id: @product.id).order("created_at DESC")
  end

  # GET /products/new
  def new
    @product = current_user.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Produto criado com sucesso.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :tag, :price, :image)
    end
end

ep3finalmentepqp-master/shop/app/helpers/products_helper.rb
module ProductsHelper
  def product_author(product)
    user_signed_in? && current_user.id == product.user_id
  end
end

ep3finalmentepqp-master/shop/app/views/products/_form.html.erb
<div class="columns">
  <div class="field is-grouped is-grouped-centered">

    <%= simple_form_for @product, html: { multipart: true } do |f| %>
    <%= f.error_notification %>
      <!--Campo para nome do produto-->
      <div class="field-body">
        <div class="field">
          <label class="label">Nome</label>
          <div class="control">
            <%= f.input :name , required: true, input_html: { class: "input"}, wrapper: false%>
          </div>
        </div>
        <!--Campo de Preço produto-->
        <div class="field">
          <label class="label">Preço:</label>
          <div class="control">
            <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false%>
          </div>
        </div>
    </div>
      <!--Campo de Descrição de produto-->
      <div class="field">
        <div class="control">
          <label class="label">Descrição:</label>
          <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false%>
        </div>
      </div>

        <div class="field is-grouped">
          <!--Dropdown de categorias-->
          <div class="control">
            <label class="label">Categoria</label>
            <div class="control has-icons-left">
              <span class="select">
                <%= f.input_field :tag, collection: Product::TAG, prompt: "Selecionar categoria" %>
              </span>
              <span class="icon is-left">
                <i class="fa fa-plus-circle fa-2x"></i>
              </span>
            </div>
          </div>

      <!--Botões p/ adicionar imagens de produto-->
         <div class="control">
           <label class="label">Adicionar imagem</label>
           <div class="file">
             <label class="file-label">
               <%= f.input :image, as: :file, input_html: { class:"file-input product-image" }, label: false, wrapper: false %>
               <span class="file-cta">
                 <span class="file-icon"><i class="fa fa-upload"></i></span>
                 <span class="file-label">Escolher um arquivo…</span>
               </span>
             </label>
           </div>
         </div>
        </div>
         <hr/>
         <!--Botões de Criar e Cancelar-->
         <div class="field is-grouped is-grouped-right">
           <div class="control">
             <%= f.button :submit, class: 'button is-info is-outlined' %>
             <%= link_to 'Cancelar', products_path, class:'button is-danger is-outlined' %>
           </div>
         </div>

       </div>
        <output id="list"></output>
      <hr/>
    <% end %>
  </div>

ep3finalmentepqp-master/shop/app/views/products/edit.html.erb
<% content_for :header do %>
<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editando Produto
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', product: @product %>
</div>

ep3finalmentepqp-master/shop/app/views/products/index.html.erb
<!--Página inicial-->
<% content_for :header do %>
  <section class="hero is-info">
    <div class="hero-body">
      <!--Lançamentos-->
      <div class="container">
        <h1 class="title">
          <i class="fa fa-bullseye" aria-hidden="true"></i>
          Últimos produtos adicionados
        </h1>
      </div>
      <hr/>
      <div class="tile is-ancestor">
        <% @products.each do |product| %>
          <!--Produtos-->
          <div class="tile is-parent">
            <article class="tile is-child box">
              <!--Imagem Produto-->
              <div class="tile is-child box">
                <figure class="image is-4by2">
                  <%= link_to image_tag(product.image_url(:thumb)), product %>
                </figure>
                <!--Tag Produto-->
                <% if product.name? %>
                <div class="name">
                  <span class="tag is-info"><%= product.tag %></span>
                </div>
                <% end %>
              </div>
              <!--Nome seguido de preço do Produto-->
              <div class="field is-grouped is-grouped-centered">
                <div class="pa3 has-text-info">
                  <h3 class="fw7 f4 title"><%= link_to product.name, product %></h3>
                  <p class="f3 fw6 pt2 price has-text-info"><%= number_to_currency(product.price) %></p>
                  <p class="control">
                    <%= link_to product, class:"navbar-item button is-info" do %>
                    <span class="icon">
                      <i class="fa fa-cart-plus has-text-primary" aria-hidden="true"></i>
                    </span>
                    <span>
                      Comprar
                    </span>
                    <% end  %>
                  <!--Verifica se o usuário é adm, caso seja, habilita a funçaõ de deletar e editar o produto-->
                  <% if current_user.try(:admin2?) %>
                    <hr/>
                    <%= link_to 'Editar', edit_product_path(product), class: "button is-small" %>
                    <%= link_to 'Deletar', product, method: :delete, data: { confirm: "Você tem certeza ?" }, class: "button is-small" %>
                  <% end %>
                </div>
              </div>
            </article>
          </div>

        <% end %>
      </div>

      <!--Top produtos-->
      <div class="container">
        <h1 class="title">
          <i class="fa fa-arrow-circle-o-up " aria-hidden="true"></i>
          Top Produtos
        </h1>
      </div>
      <hr/>
      <div class="tile is-ancestor">
        <% @products.each do |product| %>
          <!--Produtos-->
          <div class="tile is-parent">
            <article class="tile is-child box">
              <!--Imagem Produto-->
              <div class="tile is-child box">
                <figure class="image is-4by2">
                  <%= link_to image_tag(product.image_url(:thumb)), product %>
                </figure>
                <!--Tag Produto-->
                <% if product.name? %>
                <div class="name">
                  <span class="tag is-info"><%= product.tag %></span>
                </div>
                <% end %>
              </div>
              <!--Nome seguido de preço do Produto-->
              <div class="field is-grouped is-grouped-centered">
                <div class="pa3 has-text-info">
                  <h3 class="fw7 f4 title"><%= link_to product.name, product %></h3>
                  <p class="f3 fw6 pt2 price has-text-info"><%= number_to_currency(product.price) %></p>
                  <p class="control">
                    <%= link_to product, class:"navbar-item button is-info" do %>
                    <span class="icon">
                      <i class="fa fa-cart-plus has-text-primary" aria-hidden="true"></i>
                    </span>
                    <span>
                      Comprar
                    </span>
                    <% end  %>
                  <!--Verifica se o usuário é adm, caso seja, habilita a funçaõ de deletar e editar o produto-->
                  <% if product_author(product) && current_user.admin? %>
                    <hr/>
                    <%= link_to 'Editar', edit_product_path(product), class: "button is-small" %>
                    <%= link_to 'Deletar', product, method: :delete, data: { confirm: "Você tem certeza ?" }, class: "button is-small" %>
                  <% end %>
                </div>
              </div>
            </article>
          </div>

        <% end %>

    </div>
  </section>
<% end %>

ep3finalmentepqp-master/shop/app/views/products/new.html.erb
<% content_for :header do %>
<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Publicar um produto
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', product: @product %>
</div>

ep3finalmentepqp-master/shop/app/views/products/show.html.erb
<% content_for :body_class, 'bg-dark' %>

<section class="section product-show">
  <div class="tile is-ancestor">

    <div class="tile is-parent">
      <div class="tile is-child box">
        <div class="feature-image">
          <%= image_tag(@product.image_url(:default)) %>
        </div>
      </div>

      <div class="tile is-parent is-vertical">
        <article class="tile is-child box is-info">
          <div class="content pa4 mt3 bg-white border-radius-3">
            <h1 class="title is-2"><%= @product.name %></h1>
          </div>
        </article>

        <article class="tile is-child box">
            <table class="table is-narrow is-fullwidth">
               <% if @product.tag %>
               <tr>
                 <td class="has-text-weight-bold">
                   <i class="fa fa-address-card has-text-info" aria-hidden="true"></i>
                   Categoria:</td>
                 <td><%= @product.tag %></td>
               </tr>
               <% end %>
               <% if @product.price %>
               <tr>
                 <td class="has-text-weight-bold">
                   <i class="fa fa-money has-text-info" aria-hidden="true"></i>
                   Preço(R$):
                 </td>
                 <td><%= @product.price %></td>
               </tr>
               <% end %>
            </table>
            <% if user_signed_in? %>
              <%= button_to 'Adicionar ao carrinho', line_items_path(product_id: @product), class: 'button is-info add-to-cart' %>
            <% else %>
              <%= button_to 'Conecte-se para comprar', new_user_session_path, class: 'button is-info add-to-cart' %>
            <% end %>
        </article>

        <div class="tile is-child box">
          <h3 class="title is-child is-4">
            <i class="fa fa-id-badge has-text-info" aria-hidden="true"></i>
            Ficha técnica:
          </h3>
          <p"><%= @product.description %></p>
        </div>
      </div>
    </div>

  </div>

  <div class="tile is-ancestor">
    <div class="tile is-parent">
      <div class="tile is-child box">

        <h3 class="title is-child is-4">
          <i class="fa fa-star-half-o has-text-info" aria-hidden="true"></i>
          Avaliações:
        </h3>
        <article class="title is-child has-text-info">
          <% if user_signed_in? %>
          <i class="fa fa-pencil-square has-text-info" aria-hidden="true"></i>
          <%= link_to "Escreva uma análise!", new_product_review_path(@product) %>
          <% end %>
        </article>

        <% if @reviews.blank? %>
        <h3>Sem análises</h3>
        <% else %>
          <% @reviews.each do |review| %>
            <div class="reviews">

              <article class="title box is-5">
                <div class="media-content">
                  <div class="content">
                    <small class="author">Análise feita por: <%= review.user.name %></small>
                    <br>
                    <p><%= review.comment %></p>
                  </div>
                </div>


                <% if user_signed_in?%>
                  <% if current_user.try(:admin2?) -%>
                      <div class="btn-group has-text-info">
                        <%= link_to 'Editar', edit_product_review_path(@product, review.id), class: "btn btn-default" %>
                        <%= link_to 'Deletar', product_review_path(@product, review.id), data: {:confirm => "Tem certeza?"}, :method => :delete, class: "btn btn-default" %>
                      </div>
                  <% elsif review.user == current_user -%>
      	           <div class="btn-group">
                      %= link_to 'Editar', edit_product_review_path(@product, review.id), class: "btn btn-default" %>
                      <%= link_to 'Deletar', product_review_path(@product, review.id), data: {:confirm => "Tem certeza?"}, :method => :delete, class: "btn btn-default" %>
      	           </div>
                  <% end %>
                <% end %>
              </article>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <% if current_user.try(:admin2?) %>
    <%= link_to 'Editar', edit_product_path(@product), class: 'button' %>
  <% end %>
</section>