ep3finalmentepqp-master/shop/config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :products do
    resources :reviews, except: [:show, :index]
  end
  devise_for :users, controllers:  {
    registrations: 'registrations'
  }
  root 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

ep3finalmentepqp-master/shop/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_product

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.product_id = @product.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @product, notice: 'Review feita com sucesso.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @product, notice: 'Review atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy!
    redirect_to @product, notice: 'Review deletada com sucesso.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_product
      @product = Product.find(params[:product_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:score, :comment)
    end
end

ep3finalmentepqp-master/shop/app/helpers/reviews_helper.rb
module ReviewsHelper
end

ep3finalmentepqp-master/shop/app/views/reviews/_form.html.erb
<%= form_for([@product, @review]) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Análise %><br>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit raw("Criar/Atualizar Análise") %>
  </div>
<% end %>

ep3finalmentepqp-master/shop/app/views/reviews/edit.html.erb
<h1>Eh1>Editando Análise</h1>

<%= render 'form', review: @review %>

<%= link_to 'Voltar', product_path(@product) %>

ep3finalmentepqp-master/shop/app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table is-borded>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

ep3finalmentepqp-master/shop/app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', product_path(@product) %>

ep3finalmentepqp-master/shop/app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>